name: Build Windows Installer

on:
  workflow_dispatch:
    branches: [main]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Download Wix
        uses: i3h/download-release-asset@v1
        with:
          owner: wixtoolset
          repo: wix3
          tag: wix3112rtm
          file: wix311-binaries.zip
      - name: Decompress Wix
        uses: DuckSoft/extract-7z-action@v1.0
        with:
          pathSource: wix311-binaries.zip
          pathTarget: ./target/wix
      - name: Add Wix to Path
        run: echo "$HOME/target/wix" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8 -Append
      - uses: actions/checkout@v4
      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          java-version: 21
          distribution: 'temurin'
          cache: 'maven'
      - name: Download JavaFX jmods (Windows x86_64)
        run: |
          mkdir javafx-windows-x86_64
          curl -L -o javafx-jmods.zip https://download2.gluonhq.com/openjfx/21.0.6/openjfx-21.0.6_windows-x86_64_bin-jmods.zip
          Expand-Archive -Path javafx-jmods.zip -DestinationPath javafx-windows-x86_64
          del javafx-jmods.zip
      - name: Build with Maven
        run: mvn -B clean install --file pom.xml
      - name: Upload MSI
        uses: actions/upload-artifact@v4
        with:
          name: Windows-msi
          path: target/*.msi